version: "3.8"
services:
    api:
        build:
            dockerfile: Dockerfile
            context: .
        
        environment: 
           
            PORT: 3000
        ports:
            - "3000:3000"
